on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy blog to hydrogen
    steps:
    - name: Setup Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - name: Deploy
      id: deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      uses: tailscale/tailscale-deploy-github@v1
      with:
        machine-name: 'hydrogen'
    - name: Output
      run: 'echo "tarball generated and pushed: ${{ steps.hello.outputs.filename }}"'
