on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy blog to magnesium
    steps:
    - name: Deploy
      id: deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      uses: tailscale/tailscale-deploy-github@v1
      with:
        machine-name: 'magnesium'
    - name: Output
      run: 'echo "tarball generated and pushed: ${{ steps.hello.outputs.filename }}"'
